import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/Navbar";
import "bootstrap/dist/css/bootstrap.min.css";
import ImportBootstrap from "@/components/ImportBootstrap";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ego - test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <footer></footer>
        <ImportBootstrap />
      </body>
    </html>
  );
}
